title: Data Analytics Portfolio
description: sample of Data Analytics skills
theme: jekyll-theme-primer  # You can use any available GitHub Pages theme
baseurl: ""   # Leave empty unless the site is served from a subpath
url: "https://github.com/git4nader/NaderFarrPortfolio.io/"  # Replace with your GitHub Pages URL

# Plugins to extend the functionality of your site
plugins:
  - jekyll-seo-tag

markdown: kramdown   # Jekyll uses Kramdown for Markdown processing by default

paginate: 5  # Optional: For pagination of blog posts
