title: Data Analytics Portfolio
description: Sample of Data Analytics skills showcasing SQL, Tableau, and Python projects.
theme: jekyll-theme-primer
baseurl: ""   # Leave empty unless the site is served from a subpath

url: "https://git4nader.github.io/NaderFarrPortfolio.io"  # Replace with your GitHub Pages URL

# Plugins
plugins:
  - jekyll-seo-tag

# Markdown Processor
markdown: kramdown

# Pagination (if applicable)
paginate: 5
paginate_path: "/page:num/"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# Optional: Favicon
# favicon: "/assets/images/favicon.ico"

# Timezone
timezone: "America/Los_Angeles"

# Additional settings
# You can add more configurations as needed
